global class Vitality_Constants {
	public static final String ACCOUNT_LOCK_EMAIL_SUBJECT = 'Your My Hub account is locked';
    public static final String ACCOUNT_LOCK_EMAIL_SUBJECT_FR = 'Votre compte Mon carrefour est verrouillé.';
    public static final String ACCOUNT_CREATE_EMAIL_SUBJECT = 'You now have a My Hub account. Congratulations.';
    public static final String ACCOUNT_CREATE_EMAIL_SUBJECT_FR = 'Félicitations! Vous avez maintenant un compte Mon carrefour.';
	public static final String PASSWORD_CHANGE_EMAIL_SUBJECT = 'Your password for My Hub is reset';
    public static final String PASSWORD_CHANGE_EMAIL_SUBJECT_FR = 'Votre mot de passe pour accéder à Mon carrefour a été réinitialisé';
    /*Context User Changes -START*/
    public static final String REGISTRATION_EMAIL_SUBJECT_EN = 'One more step to activate your My Hub account';
    public static final String REGISTRATION_EMAIL_SUBJECT_FR = 'Il ne vous reste qu’une étape pour activer votre compte Mon carrefour';
    public static final String RESET_PASSWORD_EMAIL_SUBJECT_EN = 'Activate your My Hub password';
    public static final String RESET_PASSWORD_EMAIL_SUBJECT_FR = 'Activez votre mot de passe Mon carrefour';
    /*Context User Changes -END*/
 	public static final String ET_RESET_PASSWORD_CONFIRMATION_FR = 'ISAM Reset Password Confirmation Email for French';
    public static final String ET_RESET_PASSWORD_CONFIRMATION_EN = 'ISAM Reset Password Confirmation Email for English';
    public static final String ET_ACCOUNT_LOCK_NOTIFICATION_FR = 'ISAM Account Lock Notification French';
    public static final String ET_ACCOUNT_LOCK_NOTIFICATION_EN = 'ISAM Account Lock Notification English';
    public static final String ET_ACCOUNT_CREATE_NOTIFICATION_FR = 'ISAM Account Create Notification French';
    public static final String ET_ACCOUNT_CREATE_NOTIFICATION_EN = 'ISAM Account Create Notification English';
    /*Context User Changes -START*/
    public static final String ET_REGISTRATION_NOTIFICATION_EN = 'ISAM Registration Email for English';
    public static final String ET_REGISTRATION_NOTIFICATION_FR = 'ISAM Registration Email for French';
    public static final String ET_RESET_PASSWORD_NOTIFICATION_EN = 'ISAM Reset Password Email for English';
    public static final String ET_RESET_PASSWORD_NOTIFICATION_FR = 'ISAM Reset Password Email for French';
    /*Context User Changes -END*/
    public static final String LANG_CODE_FRENCH = 'fr_CA';
    public static final String LANG_CODE_ENGLISH = 'en_US';
    public static final String MEMBERSHIP_TERMINATED_STATUS = 'Terminated';
    public static final String ISTRUEFLAG = 'true';
    public static final String ISFALSEFLAG = 'false';
    public static final String ISERRORFLAG = 'error';
    public static final String ISSUCCESSFLAG = 'success';
    /*Context User Changes -START*/
    public static final String VITALITY_EN_SENDER = 'Manulife-My Hub';
    public static final String VITALITY_FR_SENDER = 'Manuvie - Mon carrefour';
    /*Context User Changes -END*/
}